catalog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('students/', views.StudentListView.as_view(), name='students'),
    path('student/<int:pk>', views.StudentDetailView.as_view(), name='student-detail'),
    path('teachers/', views.TeacherListView.as_view(), name='teachers'),
    path('teacher/<int:pk>', views.TeacherDetailView.as_view(), name='teacher-detail'),
]

portal/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]
# Use include() to add paths from the catalog application 
from django.urls import include

urlpatterns += [
    path('catalog/', include('catalog.urls')),
]
#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/catalog/')),
]
# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.db import models

# Create your models here.
class Specialyties(models.Model):
    """
    Model representing a book genre (e.g. Science Fiction, Non Fiction).
    """
    sp_name = models.CharField(max_length=200, help_text="Enter a student spec")
    
    def __str__(self):
        """
        String for representing the Model object (in Admin site etc.)
        """
        return self.sp_name
from django.urls import reverse #Used to generate URLs by reversing the URL patterns

class Student(models.Model):
    """
    Model representing a book (but not a specific copy of a book).
    """
    st_name = models.CharField(max_length=200)
    teacher = models.ForeignKey('Teacher', on_delete=models.SET_NULL, null=True)
    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author as a string rather than object because it hasn't been declared yet in the file.
    GPA = models.TextField(max_length=1000, help_text="Enter a GPA of the student")
    iin = models.CharField('IIN',max_length=13, help_text='13 Character <a href="https://www.iin-international.org/content/what-iin">IIN number</a>')
    specialityes = models.ManyToManyField(Specialyties, help_text="Select a spec for this student")
    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    
    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.st_name
    
    
    def get_absolute_url(self):
        """
        Returns the url to access a particular book instance.
        """
        return reverse('student-detail', args=[str(self.id)])
import uuid # Required for unique student instances

class StudentInformation(models.Model):
    """
    Model representing a specific copy of a book (i.e. that can be borrowed from the library).
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this particular book across whole library")
    student = models.ForeignKey('Student', on_delete=models.SET_NULL, null=True) 
    mail = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Magistrant'),
        ('o', 'Otchislen'),
        ('a', 'Bakalavr'),
        ('r', 'Doctorant'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='d', help_text='Student status')

    class Meta:
        ordering = ["due_back"]
        

    def __str__(self):
        """
        String for representing the Model object
        """
        return '%s (%s)' % (self.id,self.student.st_name)
class Teacher(models.Model):
    """
    Model representing an author.
    """
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_hire = models.DateField('Hire', null=True, blank=True)
    
    def get_absolute_url(self):
        """
        Returns the url to access a particular author instance.
        """
        return reverse('teacher-detail', args=[str(self.id)])
    

    def __str__(self):
        """
        String for representing the Model object.
        """
        return '%s, %s' % (self.last_name, self.first_name)

catalog/views.py
from django.shortcuts import render

# Create your views here.
from .models import Student, Teacher, StudentInformation, Specialyties

def index(request):
    """
    View function for home page of site.
    """
    # Generate counts of some of the main objects
    num_students=Student.objects.all().count()
    num_informations=StudentInformation.objects.all().count()
    # Available books (status = 'a')
    num_informations_available=StudentInformation.objects.filter(status__exact='a').count()
    num_teachers=Teacher.objects.count()  # The 'all()' is implied by default.
    
    # Render the HTML template index.html with the data in the context variable
    return render(
        request,
        'index.html',
        context={'num_students':num_students,'num_informations':num_informations,'num_informations_available':num_informations_available,'num_teachers':num_teachers},
    )
from django.views import generic

class StudentListView(generic.ListView):
    model = Student
    paginate_by = 2
class StudentDetailView(generic.DetailView):
    model = Student
from django.views import generic

class TeacherListView(generic.ListView):
    model = Teacher
    paginate_by = 2
class TeacherDetailView(generic.DetailView):
    model = Teacher

catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  
  {% block title %}<title>Satbayev University</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

  <div class="container-fluid">

    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
      <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'students' %}">All students</a></li>
          <li><a href="{% url 'teachers' %}">All teachers</a></li>
      </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">
      {% block content %}{% endblock %}

{% block pagination %}
  {% if is_paginated %}
      <div class="pagination">
          <span class="page-links">
              {% if page_obj.has_previous %}
                  <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
              {% endif %}
              <span class="page-current">
                  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
              </span>
              {% if page_obj.has_next %}
                  <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
              {% endif %}
          </span>
      </div>
  {% endif %}
{% endblock %}
      </div>
    </div>

  </div>
</body>
</html>

catalog/templates/catalog/student_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ student.st_name }}</h1>

  <p><strong>Teacher:</strong> <a href="{% url 'teacher-detail' student.teacher.pk %}">{{ student.teacher }}</a> 
  <p><strong>GPA:</strong> {{ student.GPA }}</p>
  <p><strong>IIN:</strong> {{ student.iin }}</p> 
  <p><strong>Language:</strong> {{ student.language }}</p>  
  <p><strong>Spec:</strong> {% for spec in student.spec.all %} {{ spec }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>  

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in student.studentinformation_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Mail:</strong> {{copy.mail}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/student_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Student List</h1>

    {% if student_list %}
    <ul>

      {% for student in student_list %}
      <li>
        <a href="{{ student.get_absolute_url }}">{{ student.st_name }}</a> ({{student.teacher}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no students in the University.</p>
    {% endif %}       
{% endblock %}

catalog/templates/catalog/teacher_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Teacher: {{ teacher.last_name }} {{ teacher.first_name }}</h1>

  <p><strong>Students:</strong> <a href="http://localhost:8000/catalog/students">Student_list</a></p>
  <p><strong>last_name:</strong> {{ teacher.last_name }}</p>
  <p><strong>firs_name:</strong> {{ teacher.first_name }}</p> 
  <div style="margin-left:20px;margin-top:20px">
  <p><strong>date_of_birth:</strong> {{ teacher.date_of_birth }}</p>  
  <p><strong>date_hire:</strong> {{ teacher.date_hire }}</p>  

  

  </div>
{% endblock %}

catalog/templates/catalog/teacher_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Teacher List</h1>

    {% if teacher_list %}
    <ul>

      {% for teacher in teacher_list %}
      <li>
        <a href="{{ teacher.get_absolute_url }}">{{ teacher.last_name }},{{teacher.first_name}}</a> ({{teacher.date_hire}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no teachers in the University.</p>
    {% endif %}       
{% endblock %}

catalog/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Satbayev University Home</h1>

  <p>Welcome to <em>LocalLibrary</em>, a very basic Django website developed as a tutorial example on the Mozilla Developer Network.</p>

<h2>Dynamic content</h2>

  <p>The portal has the following record counts:</p>
  <ul>
    <li><strong>Students:</strong> {{ num_students }}</li>
    <li><strong>Informs:</strong> {{ num_informations }}</li>
    <li><strong>Informs available:</strong> {{ num_informations_available }}</li>
    <li><strong>Teachers:</strong> {{ num_teachers }}</li>
  </ul>

{% endblock %}